token = ""

application_channel = "application"
eligible_role = "18"
subscription_channel = "botspam"

ranks = ["yuri", "ero"]

cache_root = 'cache/'
text_path = 'langs/kakuri.toml'

# case-insensitive
yes_words = ['はい', 'yes', 'そうです']
no_words = ['いいえ', 'no']
