token = ""

application_channel = "botspam"
eligible_role = "dummy"
subscription_channel = "botspam2"

ranks = ["foo", "bar"]

cache_root = 'cache/'
text_path = 'langs/kakuri.toml'

# case-insensitive
yes_words = ['はい', 'yes', 'そうです']
no_words = ['いいえ', 'no']
